# Use the official Node.js image from the Docker Hub
FROM node:latest

# Create and change to the app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy app source code to the container
COPY . .

# Expose the port the app runs on
EXPOSE 8080

# Install nodemon globally
RUN npm install -g nodemon

# Define the command to run the app with nodemon
CMD ["nodemon", "index.js"]
